spring:
  mvc:
    locale: ko_KR
    favicon:
      enabled: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
      
  resources:
    chain:
      gzipped: true
      cache: true

  http:
    encoding:
      charset: UTF-8

  servlet:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1024Mb

logging:
  level:
    root: info
    com:
      mobigen: debug

server:
    port: 9090
    servlet:
      session:
        cookie:
          name: recommendedSystem-session-id
    compression:
      enabled: true
    tomcat:
      uri-encoding: UTF-8
    error:
      whitelabel:
        enabled: true


mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: com.mobigen, com.skt
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: PARTIAL
    default-executor-type: SIMPLE
    default-statement-timeout: 180
    safe-row-bounds-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: SESSION
    jdbc-type-for-null: OTHER
---
spring:
  profiles: local
  datasource:
    #type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.101.2:1521:ORA
    username: oksusu3
    password: hellooksusu

    dbcp2:
      initial-size: 7
      max-total: 100
      pool-prepared-statements: true

config:
  img-path: /oksusu-demopage-img/

---
spring:
  profiles: dev
  datasource:
    #type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.101.2:1521:ORA
    username: oksusu3
    password: hellooksusu

    dbcp2:
      initial-size: 7
      max-total: 100
      pool-prepared-statements: true

config:
  img-path: /oksusu-demopage-img/

#    tomcat:
#      default-auto-commit: false
#      initial-size: 10
#      min-idle: 10
#      max-idle: 30
#      max-wait: 10000
#      test-on-borrow: true
#      test-on-return: true
#      test-while-idle: true
#      time-between-eviction-runs-millis: 130000
#      min-evictable-idle-time-millis: 120000
#      num-tests-per-eviction-run: 20
#      remove-abandoned-timeout: 30
#      remove-abandoned: true
#      log-abandoned: false
#      validation-query: select 1 from dual